POSITION_TEMPLATES = [
    # Tech (5)
    {
        "id": "dev-fullstack",
        "title": "Developpeur Full Stack",
        "description": "Nous recherchons un developpeur full stack experimente pour rejoindre notre equipe. Vous serez responsable du developpement d'applications web modernes, de la conception a la mise en production.",
        "required_skills": ["Python", "JavaScript", "React", "SQL", "Git", "REST API"],
        "seniority_level": "mid",
        "custom_questions": [
            "Decrivez un projet technique complexe que vous avez mene a bien",
            "Comment gerez-vous les conflits de merge dans une equipe ?",
            "Quelle est votre approche pour optimiser les performances d'une application web ?",
        ],
        "category": "tech",
    },
    {
        "id": "dev-backend",
        "title": "Developpeur Backend",
        "description": "Rejoignez notre equipe backend pour concevoir et developper des API robustes et scalables. Vous travaillerez sur des microservices et participerez aux choix architecturaux.",
        "required_skills": ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "Celery"],
        "seniority_level": "mid",
        "custom_questions": [
            "Expliquez votre experience avec les architectures microservices",
            "Comment assurez-vous la scalabilite d'une API ?",
            "Decrivez votre approche pour le debugging en production",
        ],
        "category": "tech",
    },
    {
        "id": "dev-frontend",
        "title": "Developpeur Frontend",
        "description": "Nous cherchons un developpeur frontend passionne pour creer des interfaces utilisateur modernes et performantes. Vous collaborerez etroitement avec les designers et le backend.",
        "required_skills": ["React", "TypeScript", "Tailwind CSS", "REST API", "Git"],
        "seniority_level": "mid",
        "custom_questions": [
            "Quelle est votre experience avec React et ses hooks ?",
            "Comment gerez-vous l'etat global dans une application complexe ?",
            "Expliquez votre approche pour l'accessibilite web (a11y)",
        ],
        "category": "tech",
    },
    {
        "id": "devops",
        "title": "Ingenieur DevOps",
        "description": "Rejoignez notre equipe infrastructure pour automatiser nos deployements et garantir la fiabilite de nos services. Vous serez en charge de la CI/CD et du monitoring.",
        "required_skills": ["Docker", "Kubernetes", "CI/CD", "Linux", "Python", "Terraform"],
        "seniority_level": "senior",
        "custom_questions": [
            "Decrivez votre experience avec Kubernetes en production",
            "Comment mettez-vous en place une strategie de monitoring efficace ?",
            "Quelle est votre approche pour gerer les incidents critiques ?",
        ],
        "category": "tech",
    },
    {
        "id": "data-analyst",
        "title": "Data Analyst",
        "description": "Nous recherchons un data analyst pour transformer nos donnees en insights actionnables. Vous travaillerez sur des tableaux de bord et des analyses predictives.",
        "required_skills": ["SQL", "Python", "Excel", "Power BI", "Statistiques"],
        "seniority_level": "mid",
        "custom_questions": [
            "Decrivez un projet d'analyse de donnees dont vous etes fier",
            "Comment communiquez-vous vos insights aux parties prenantes non techniques ?",
            "Quelle est votre experience avec les outils de visualisation ?",
        ],
        "category": "tech",
    },
    # Business (3)
    {
        "id": "account-manager",
        "title": "Charge de Compte",
        "description": "Rejoignez notre equipe commerciale pour gerer un portefeuille de clients B2B. Vous serez responsable de la relation client, du suivi des contrats et du developpement du chiffre d'affaires.",
        "required_skills": ["Relation client", "Negociation", "CRM", "Vente B2B", "Communication"],
        "seniority_level": "mid",
        "custom_questions": [
            "Decrivez comment vous avez fidelise un client difficile",
            "Quelle est votre approche pour identifier les opportunites de upsell ?",
            "Comment gerez-vous les priorites avec plusieurs comptes simultanement ?",
        ],
        "category": "business",
    },
    {
        "id": "business-developer",
        "title": "Business Developer",
        "description": "Nous cherchons un business developer dynamique pour developper notre presence sur le marche marocain. Vous prospecterez de nouveaux clients et negocierez des partenariats strategiques.",
        "required_skills": ["Prospection", "Negociation", "Vente B2B", "Marketing", "Presentation"],
        "seniority_level": "mid",
        "custom_questions": [
            "Decrivez votre strategie de prospection pour un nouveau marche",
            "Comment preparez-vous une negociation commerciale importante ?",
            "Parlez-nous d'un deal complexe que vous avez conclu",
        ],
        "category": "business",
    },
    {
        "id": "customer-success",
        "title": "Customer Success Manager",
        "description": "Rejoignez notre equipe pour assurer la reussite de nos clients SaaS. Vous les accompagnerez dans l'adoption de notre solution et maximiserez leur satisfaction.",
        "required_skills": ["Relation client", "Onboarding", "SaaS", "Communication", "Resolution de problemes"],
        "seniority_level": "junior",
        "custom_questions": [
            "Comment mesurez-vous la satisfaction client ?",
            "Decrivez comment vous avez aide un client a atteindre ses objectifs",
            "Quelle est votre approche pour reduire le churn ?",
        ],
        "category": "business",
    },
    # Marketing (2)
    {
        "id": "digital-marketing",
        "title": "Responsable Marketing Digital",
        "description": "Nous recherchons un responsable marketing digital pour piloter notre strategie d'acquisition en ligne. SEO, SEA, social media et content marketing seront vos leviers.",
        "required_skills": ["SEO", "SEA", "Google Analytics", "Facebook Ads", "Content Marketing"],
        "seniority_level": "mid",
        "custom_questions": [
            "Decrivez une campagne digitale que vous avez pilotee avec succes",
            "Comment optimisez-vous le ROI de vos campagnes publicitaires ?",
            "Quelle est votre experience avec le marketing automation ?",
        ],
        "category": "marketing",
    },
    {
        "id": "content-manager",
        "title": "Content Manager",
        "description": "Rejoignez notre equipe marketing pour creer du contenu engageant sur tous nos canaux. Blog, newsletters, social media, vous serez le gardien de notre voix de marque.",
        "required_skills": ["Redaction", "SEO", "WordPress", "Social Media", "Creativite"],
        "seniority_level": "junior",
        "custom_questions": [
            "Montrez-nous des exemples de contenus que vous avez crees",
            "Comment adaptez-vous votre ton selon les canaux de communication ?",
            "Quelle est votre approche pour generer des idees de contenu ?",
        ],
        "category": "marketing",
    },
    # Finance (2)
    {
        "id": "comptable",
        "title": "Comptable",
        "description": "Nous recherchons un comptable experimente pour gerer la comptabilite generale de l'entreprise, la preparation des bilans et les declarations fiscales.",
        "required_skills": ["Comptabilite generale", "Fiscalite", "Excel", "ERP", "Normes IFRS"],
        "seniority_level": "mid",
        "custom_questions": [
            "Decrivez votre experience avec les clotures comptables",
            "Comment gerez-vous les echeances fiscales multiples ?",
            "Quelle est votre maitrise des normes comptables marocaines ?",
        ],
        "category": "finance",
    },
    {
        "id": "controleur-gestion",
        "title": "Controleur de Gestion",
        "description": "Rejoignez notre equipe finance pour piloter la performance de l'entreprise. Budgets, reporting, analyses de rentabilite seront au coeur de vos missions.",
        "required_skills": ["Controle de gestion", "Budgets", "Excel", "Power BI", "Analyse financiere"],
        "seniority_level": "mid",
        "custom_questions": [
            "Decrivez comment vous avez ameliore la rentabilite d'une activite",
            "Quelle est votre approche pour construire un budget annuel ?",
            "Comment communiquez-vous les ecarts budgetaires aux operationnels ?",
        ],
        "category": "finance",
    },
    # Operations (2)
    {
        "id": "chef-projet",
        "title": "Chef de Projet",
        "description": "Nous cherchons un chef de projet pour piloter nos projets strategiques. Vous coordonnerez les equipes, gererez les plannings et assurerez la livraison dans les delais.",
        "required_skills": ["Gestion de projet", "Agile", "Jira", "Communication", "Leadership"],
        "seniority_level": "mid",
        "custom_questions": [
            "Decrivez un projet complexe que vous avez mene a bien",
            "Comment gerez-vous les risques et les imprevus ?",
            "Quelle est votre experience avec les methodologies Agile/Scrum ?",
        ],
        "category": "operations",
    },
    {
        "id": "responsable-logistique",
        "title": "Responsable Logistique",
        "description": "Rejoignez notre equipe operations pour optimiser notre chaine logistique. Approvisionnements, stocks, livraisons seront sous votre responsabilite.",
        "required_skills": ["Logistique", "Supply Chain", "Gestion de stock", "Excel", "ERP"],
        "seniority_level": "mid",
        "custom_questions": [
            "Decrivez comment vous avez optimise une chaine logistique",
            "Comment gerez-vous les ruptures de stock ?",
            "Quelle est votre experience avec les outils WMS/TMS ?",
        ],
        "category": "operations",
    },
    # HR (1)
    {
        "id": "rh-generaliste",
        "title": "Charge de Ressources Humaines",
        "description": "Nous recherchons un RH generaliste pour accompagner nos collaborateurs tout au long de leur parcours. Recrutement, formation, paie, relations sociales seront vos missions.",
        "required_skills": ["Recrutement", "Gestion RH", "Droit du travail", "Paie", "Communication"],
        "seniority_level": "mid",
        "custom_questions": [
            "Decrivez votre processus de recrutement ideal",
            "Comment gerez-vous les conflits entre collaborateurs ?",
            "Quelle est votre connaissance du droit du travail marocain ?",
        ],
        "category": "hr",
    },
]
