"""Twilio conversation webhooks — drives the interview flow.

For each call, Twilio hits these endpoints in sequence:
  1. POST /webhooks/conv/voice          — entry point (candidate picks up)
  2. POST /webhooks/conv/answer (loop)  — each candidate answer
  3. (final) <Hangup/> in TwiML

Audio playback strategy (after VOICE-02 / Option 1, mai 2026)
------------------------------------------------------------
Every prompt is pre-generated by `pre_generate_interview_audio` (worker
`telephony.initiate_call`) using the configured TTSProvider (edge-tts by
default; OpenAI nova if `TTS_PROVIDER=openai`). The
resulting URLs land in `interview.tts_audio_urls`.

In-call we prefer `<Play>{url}</Play>` to play those pre-generated MP3s.
When an URL is missing (legacy interview without pre-gen, or transient
storage error), we fall back to `<Say voice="Polly.Lea">` so the call never
breaks. The fallback also catches dynamic phrases we don't pre-generate
(generic error messages "Entretien non trouvé", etc.).

Before VOICE-02 the in-call audio was 100% `<Say> Polly Lea`, ignoring the
pre-generated MinIO assets — see `design-review/VOICE_BASELINE.md` for the
audit that surfaced the dead code path.
"""
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

import structlog
from fastapi import APIRouter, Form, Query, Request
from fastapi.responses import Response
from sqlalchemy import select

from app.core.config import get_settings
from app.core.database import async_session
from app.models.interview import Interview
from app.services.call_safety import classify_answer, decide_action

logger = structlog.get_logger()

router = APIRouter(prefix="/webhooks/conv", tags=["webhooks-conversation"])

# Default Twilio voice used when we have to fall back to `<Say>`. Polly Lea
# remains the most natural FR voice available natively in TwiML. The
# pre-generated `<Play>` path is preferred precisely because Polly Lea is
# the weakest link in the perceived realism (see VOICE_BASELINE.md §1).
FALLBACK_TWILIO_VOICE = "Polly.Lea"
FALLBACK_TWILIO_LANGUAGE = "fr-FR"


def _escape_xml(text: str) -> str:
    """Escape text for safe XML inclusion in TwiML."""
    if not text:
        return ""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )


def _build_twiml_response(content: str) -> Response:
    """Build TwiML response with proper XML headers."""
    xml = f'<?xml version="1.0" encoding="UTF-8"?>\n{content}'
    return Response(content=xml, media_type="application/xml")


def _say_or_play(text: str, audio_url: Optional[str]) -> str:
    """Return a TwiML fragment that prefers `<Play>` over `<Say>`.

    Args:
        text: Fallback text when `audio_url` is missing or unusable.
        audio_url: Presigned MinIO URL for a pre-generated MP3 (from
            `interview.tts_audio_urls`). If None or empty, fall back to a
            synchronous `<Say>` rendered by Twilio's Polly Lea voice.

    Returns:
        A TwiML XML fragment, ready to be embedded in a `<Response>`.
    """
    if audio_url:
        return f"<Play>{_escape_xml(audio_url)}</Play>"
    return (
        f'<Say language="{FALLBACK_TWILIO_LANGUAGE}" voice="{FALLBACK_TWILIO_VOICE}">'
        f"{_escape_xml(text)}</Say>"
    )


def _tts_url(tts_urls: Optional[dict], key: str) -> Optional[str]:
    """Safe accessor for `interview.tts_audio_urls`. Returns None if the
    dict is missing or the key is absent (legacy interview, or pre-gen
    failed and only stored a subset)."""
    if not tts_urls:
        return None
    return tts_urls.get(key)


def _pick_backchannel(tts_urls: Optional[dict], question_idx: int) -> str:
    """Return a TwiML fragment for a short backchannel interjection (VOICE-08).

    Uses `question_idx` deterministically to alternate between the pre-generated
    clips — keeps the rotation simple, predictable for testing, and avoids
    consecutive identical clips. Returns empty string if no backchannel was
    pre-generated (legacy interview).

    Played before the next question/transition in TwiML to humanize the
    handover and lightly mask webhook round-trip latency.
    """
    if not tts_urls:
        return ""
    # Convention: backchannel_0..backchannel_4 stored by pre_generate_interview_audio
    candidates = [
        tts_urls.get(f"backchannel_{i}") for i in range(5)
    ]
    candidates = [u for u in candidates if u]
    if not candidates:
        return ""
    url = candidates[question_idx % len(candidates)]
    return f"<Play>{_escape_xml(url)}</Play>"


@router.post("/voice")
async def conversation_voice_handler(
    request: Request,
    interview_id: str = Query(""),
) -> Response:
    """
    Entry point for incoming call. Twilio calls this when candidate picks up.
    Returns TwiML with intro + Q0, preferring pre-generated audio URLs.
    """
    logger.info("conversation_voice_handler_start", interview_id=interview_id)

    questions: list[dict] = []
    candidate_name = "candidat"
    tts_urls: Optional[dict] = None

    if interview_id:
        try:
            async with async_session() as db:
                result = await db.execute(
                    select(Interview).where(Interview.id == UUID(interview_id))
                )
                interview = result.scalar_one_or_none()
                if interview:
                    questions = interview.questions_asked or []
                    tts_urls = interview.tts_audio_urls or None

                    # Fetch candidate name for personalization
                    if interview.candidate_id:
                        from app.models.candidate import Candidate

                        cand_result = await db.execute(
                            select(Candidate).where(Candidate.id == interview.candidate_id)
                        )
                        candidate = cand_result.scalar_one_or_none()
                        if candidate:
                            candidate_name = candidate.name or "candidat"
        except Exception as e:
            logger.error("conversation_voice_handler_db_error", interview_id=interview_id, error=str(e))

    if not questions:
        logger.warning("no_questions_found", interview_id=interview_id)
        return _build_twiml_response(
            "<Response>"
            + _say_or_play(
                "Il y a eu un problème technique. Veuillez réessayer plus tard.",
                None,  # error case: always fallback
            )
            + "</Response>"
        )

    settings = get_settings()
    timeout = settings.CONVERSATION_GATHER_TIMEOUT

    # Intro & first question — text kept as fallback when pre-gen URL is absent.
    # Persona Léa + transparence Art. 50 (synchro avec tts_service.py).
    intro_text = (
        f"Bonjour {candidate_name}, je suis Léa, l'assistante IA de recrutement. "
        "Cet entretien est conduit par une intelligence artificielle, "
        "et il est enregistré avec votre consentement. "
        "Je vais vous poser trois questions courtes. "
        "Prenez le temps de répondre, et si une question n'est pas claire, dites-le moi. "
        "On commence."
    )
    q0_text = questions[0].get("text", "") if questions else ""
    q0_full = f"Première question. {q0_text}"

    intro_fragment = _say_or_play(intro_text, _tts_url(tts_urls, "intro"))
    q0_fragment = _say_or_play(q0_full, _tts_url(tts_urls, "q0"))

    twiml = (
        "<Response>"
        f"  {intro_fragment}"
        f'  <Gather input="speech" timeout="{timeout}" speechTimeout="2" actionOnEmptyResult="true" '
        f'language="fr-FR" '
        f'action="/api/v1/webhooks/conv/answer?interview_id={interview_id}&amp;question_idx=0&amp;retry_count=0" '
        f'method="POST">'
        f"    {q0_fragment}"
        f"  </Gather>"
        f'  <Redirect>/api/v1/webhooks/conv/answer?interview_id={interview_id}&amp;question_idx=0&amp;retry_count=0</Redirect>'
        "</Response>"
    )

    logger.info(
        "conversation_voice_handler_success",
        interview_id=interview_id,
        candidate_name=candidate_name,
        num_questions=len(questions),
        used_pregenerated_audio=bool(tts_urls),
    )
    return _build_twiml_response(twiml)


@router.post("/answer")
async def conversation_answer_handler(
    request: Request,
    interview_id: str = Query(""),
    question_idx: int = Query(0),
    retry_count: int = Query(0),
    SpeechResult: str = Form(""),
    Confidence: str = Form("0"),
    CallStatus: str = Form(""),
) -> Response:
    """Handle each candidate answer. Called by Twilio after Gather completes.

    Steps:
      1. Load interview + tts_audio_urls from DB
      2. Run safety classification on SpeechResult
      3. Persist per-question metric
      4. Decide: continue | retry | redirect | skip | confirm_reask | outro
      5. Return next TwiML — preferring <Play> over <Say> for every prompt
    """
    logger.info(
        "conversation_answer_handler_start",
        interview_id=interview_id,
        question_idx=question_idx,
        retry_count=retry_count,
        twilio_confidence=Confidence,
    )

    confidence_float = float(Confidence or 0)
    settings = get_settings()
    questions: list[dict] = []
    tts_urls: Optional[dict] = None

    # Load interview from DB (questions + tts URLs)
    try:
        async with async_session() as db:
            result = await db.execute(
                select(Interview).where(Interview.id == UUID(interview_id))
            )
            interview = result.scalar_one_or_none()
            if not interview:
                logger.error("interview_not_found", interview_id=interview_id)
                return _build_twiml_response(
                    "<Response>"
                    + _say_or_play("Entretien non trouvé.", None)
                    + "</Response>"
                )
            questions = interview.questions_asked or []
            tts_urls = interview.tts_audio_urls or None
    except Exception as e:
        logger.error(
            "conversation_answer_handler_db_load_error",
            interview_id=interview_id,
            error=str(e),
        )
        return _build_twiml_response(
            "<Response>"
            + _say_or_play("Erreur technique.", None)
            + "</Response>"
        )

    # Safety classification
    question_text = questions[question_idx].get("text", "") if question_idx < len(questions) else ""
    safety_result = await classify_answer(
        speech_result=SpeechResult,
        confidence=confidence_float,
        question_id=question_idx,
        question_text=question_text,
    )

    # Decide action based on safety check only (simplified for better UX)
    # TODO: Add quality evaluation in post-processing (after transcription)
    action = decide_action(safety_result, retry_count, settings.CONVERSATION_MAX_RETRIES)

    # If off-scope (user asked a question), ask for confirmation
    if safety_result.label.value == "off_scope":
        action = "confirm_reask"

    # Persist metric
    metric = {
        "question_idx": question_idx,
        "question_id": questions[question_idx].get("id", question_idx)
        if question_idx < len(questions)
        else question_idx,
        "partial_transcript": SpeechResult[:500] if SpeechResult else "",
        "twilio_confidence": confidence_float,
        "retry_count": retry_count,
        "safety_classification": safety_result.label.value,
        "safety_confidence": safety_result.confidence,
        "action_taken": action,
        "answered_at_utc": datetime.now(timezone.utc).isoformat(),
    }

    try:
        async with async_session() as db:
            result = await db.execute(
                select(Interview).where(Interview.id == UUID(interview_id))
            )
            interview = result.scalar_one_or_none()
            if interview:
                existing = interview.conversation_metrics or []
                existing = [m for m in existing if m.get("question_idx") != question_idx]
                existing.append(metric)
                interview.conversation_metrics = existing
                await db.commit()
                logger.info("metric_persisted", interview_id=interview_id, question_idx=question_idx)
    except Exception as e:
        logger.error(
            "metric_persistence_error",
            interview_id=interview_id,
            question_idx=question_idx,
            error=str(e),
        )

    # Build next TwiML based on action
    timeout = settings.CONVERSATION_GATHER_TIMEOUT

    # confirm_reask: ask if they want to submit a potentially off-scope answer
    if action == "confirm_reask":
        confirm_text = (
            "Je veux m'assurer d'avoir bien compris : "
            "souhaitez-vous vraiment donner cette réponse, "
            f"ou préférez-vous reprendre la question ? Elle portait sur : {question_text}"
        )
        confirm_fragment = _say_or_play(
            confirm_text, _tts_url(tts_urls, f"confirm_reask_q{question_idx}")
        )
        twiml = (
            "<Response>"
            f'  <Gather input="speech" timeout="{timeout}" speechTimeout="2" actionOnEmptyResult="true" '
            f'language="fr-FR" '
            f'action="/api/v1/webhooks/conv/answer?interview_id={interview_id}&amp;question_idx={question_idx}&amp;retry_count={retry_count + 1}" '
            f'method="POST">'
            f"    {confirm_fragment}"
            f"  </Gather>"
            f'  <Redirect>/api/v1/webhooks/conv/answer?interview_id={interview_id}&amp;question_idx={question_idx}&amp;retry_count={retry_count + 1}</Redirect>'
            "</Response>"
        )
        logger.info(
            "confirm_reask_twiml_returned",
            interview_id=interview_id,
            question_idx=question_idx,
            reason="poor_quality",
            used_pregenerated_audio=bool(_tts_url(tts_urls, f"confirm_reask_q{question_idx}")),
        )
        return _build_twiml_response(twiml)

    if action == "retry" and retry_count < settings.CONVERSATION_MAX_RETRIES:
        retry_text = (
            f"Je n'ai pas tout à fait saisi. Pouvez-vous reformuler ou répéter ? "
            f"La question portait sur : {question_text}"
        )
        retry_fragment = _say_or_play(retry_text, _tts_url(tts_urls, f"retry_q{question_idx}"))

        twiml = (
            "<Response>"
            f'  <Gather input="speech" timeout="{timeout}" speechTimeout="2" actionOnEmptyResult="true" '
            f'language="fr-FR" '
            f'action="/api/v1/webhooks/conv/answer?interview_id={interview_id}&amp;question_idx={question_idx}&amp;retry_count={retry_count + 1}" '
            f'method="POST">'
            f"    {retry_fragment}"
            f"  </Gather>"
            f'  <Redirect>/api/v1/webhooks/conv/answer?interview_id={interview_id}&amp;question_idx={question_idx}&amp;retry_count={retry_count + 1}</Redirect>'
            "</Response>"
        )
        logger.info(
            "retry_twiml_returned",
            interview_id=interview_id,
            question_idx=question_idx,
            retry_count=retry_count + 1,
            used_pregenerated_audio=bool(_tts_url(tts_urls, f"retry_q{question_idx}")),
        )
        return _build_twiml_response(twiml)

    # Move to next question
    next_idx = question_idx + 1

    if next_idx >= len(questions):
        # Outro — rappel transparence IA + handoff humain (Art. 50 + revue humaine)
        outro_text = (
            "Voilà, c'est tout pour moi. Merci d'avoir pris le temps de répondre. "
            "Cet entretien IA va être analysé, et un recruteur humain vous recontactera "
            "dans les prochains jours avec un retour. Bonne journée."
        )
        outro_fragment = _say_or_play(outro_text, _tts_url(tts_urls, "outro"))
        twiml = (
            "<Response>"
            f"  {outro_fragment}"
            f"  <Hangup/>"
            "</Response>"
        )
        logger.info(
            "outro_twiml_returned",
            interview_id=interview_id,
            total_questions=len(questions),
            used_pregenerated_audio=bool(_tts_url(tts_urls, "outro")),
        )
        return _build_twiml_response(twiml)

    if action == "redirect":
        # Off-scope/injection redirect, then next question
        redirect_text = (
            "Je préfère rester sur les questions de l'entretien. "
            "Revenons-y."
        )
        next_text = questions[next_idx].get("text", "") if next_idx < len(questions) else ""
        # Transitions naturelles synchro avec tts_service.py transitions[]
        _transitions = [
            "Première question.",
            "Deuxième question.",
            "Et voici la dernière.",
            "On enchaîne.",
            "Question suivante.",
            "Continuons.",
        ]
        _trans = _transitions[min(next_idx, len(_transitions) - 1)]
        next_full = f"{_trans} {next_text}"

        redirect_fragment = _say_or_play(redirect_text, _tts_url(tts_urls, "off_scope_redirect"))
        next_fragment = _say_or_play(next_full, _tts_url(tts_urls, f"q{next_idx}"))

        twiml = (
            "<Response>"
            f"  {redirect_fragment}"
            f'  <Gather input="speech" timeout="{timeout}" speechTimeout="2" actionOnEmptyResult="true" '
            f'language="fr-FR" '
            f'action="/api/v1/webhooks/conv/answer?interview_id={interview_id}&amp;question_idx={next_idx}&amp;retry_count=0" '
            f'method="POST">'
            f"    {next_fragment}"
            f"  </Gather>"
            f'  <Redirect>/api/v1/webhooks/conv/answer?interview_id={interview_id}&amp;question_idx={next_idx}&amp;retry_count=0</Redirect>'
            "</Response>"
        )
        logger.info(
            "redirect_twiml_returned",
            interview_id=interview_id,
            from_question_idx=question_idx,
            to_question_idx=next_idx,
            reason=safety_result.label.value,
            used_pregenerated_audio=bool(_tts_url(tts_urls, "off_scope_redirect")),
        )
        return _build_twiml_response(twiml)

    # Normal continue to next question
    next_text = questions[next_idx].get("text", "") if next_idx < len(questions) else ""
    # Transitions naturelles synchro avec tts_service.py transitions[]
    _transitions = [
        "Première question.",
        "Deuxième question.",
        "Et voici la dernière.",
        "On enchaîne.",
        "Question suivante.",
        "Continuons.",
    ]
    _trans = _transitions[min(next_idx, len(_transitions) - 1)]
    next_full = f"{_trans} {next_text}"
    next_fragment = _say_or_play(next_full, _tts_url(tts_urls, f"q{next_idx}"))

    # VOICE-08 backchannel — petit "d'accord/bien/hmm" avant la transition,
    # humanise l'enchaînement. Vide pour les interviews legacy sans pre-gen.
    backchannel = _pick_backchannel(tts_urls, question_idx)

    twiml = (
        "<Response>"
        f"  {backchannel}"
        f'  <Gather input="speech" timeout="{timeout}" speechTimeout="2" actionOnEmptyResult="true" '
        f'language="fr-FR" '
        f'action="/api/v1/webhooks/conv/answer?interview_id={interview_id}&amp;question_idx={next_idx}&amp;retry_count=0" '
        f'method="POST">'
        f"    {next_fragment}"
        f"  </Gather>"
        f'  <Redirect>/api/v1/webhooks/conv/answer?interview_id={interview_id}&amp;question_idx={next_idx}&amp;retry_count=0</Redirect>'
        "</Response>"
    )
    logger.info(
        "continue_twiml_returned",
        interview_id=interview_id,
        from_question_idx=question_idx,
        to_question_idx=next_idx,
        used_pregenerated_audio=bool(_tts_url(tts_urls, f"q{next_idx}")),
    )
    return _build_twiml_response(twiml)
