"""Add conversation fields to interviews

Revision ID: a1b2c3d4e6f7
Revises: f1a2b3c4d5e6
Create Date: 2026-04-09 21:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e6f7'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('tts_audio_urls', sa.JSON(), nullable=True))
    op.add_column('interviews', sa.Column('conversation_metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'conversation_metrics')
    op.drop_column('interviews', 'tts_audio_urls')
    # ### end Alembic commands ###
