"""add_missing_tenant_columns

Revision ID: ba70d609fe91
Revises: 8e237fedbbd9
Create Date: 2026-04-13 16:19:28.491533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ba70d609fe91'
down_revision: Union[str, None] = '8e237fedbbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_candidate_position'), table_name='applications')
    op.drop_index(op.f('ix_applications_position_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_constraint(op.f('bulk_imports_position_id_fkey'), 'bulk_imports', type_='foreignkey')
    op.drop_constraint(op.f('bulk_imports_tenant_id_fkey'), 'bulk_imports', type_='foreignkey')
    op.drop_constraint(op.f('bulk_imports_user_id_fkey'), 'bulk_imports', type_='foreignkey')
    op.create_foreign_key(None, 'bulk_imports', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(None, 'bulk_imports', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bulk_imports', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'email_verification_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('interviews', 'tts_audio_urls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('interviews', 'conversation_metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_match_scores_candidate_id'), table_name='match_scores')
    op.drop_index(op.f('ix_match_scores_position_id'), table_name='match_scores')
    op.drop_index(op.f('ix_match_scores_score'), table_name='match_scores')
    op.drop_index(op.f('ix_match_scores_tenant_id'), table_name='match_scores')
    op.drop_index(op.f('ix_match_sessions_status'), table_name='match_sessions')
    op.drop_index(op.f('ix_match_sessions_tenant_id'), table_name='match_sessions')
    op.drop_index(op.f('ix_notifications_user_read'), table_name='notifications')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_tenant_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('scorecards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_scorecards_evaluator_id'), table_name='scorecards')
    op.drop_index(op.f('ix_scorecards_interview_id'), table_name='scorecards')
    op.add_column('tenants', sa.Column('scoring_skills_weight', sa.Integer(), nullable=False))
    op.add_column('tenants', sa.Column('scoring_experience_weight', sa.Integer(), nullable=False))
    op.add_column('tenants', sa.Column('scoring_education_weight', sa.Integer(), nullable=False))
    op.add_column('tenants', sa.Column('compliance_framework', sa.String(length=50), nullable=False))
    op.add_column('tenants', sa.Column('compliance_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'compliance_config')
    op.drop_column('tenants', 'compliance_framework')
    op.drop_column('tenants', 'scoring_education_weight')
    op.drop_column('tenants', 'scoring_experience_weight')
    op.drop_column('tenants', 'scoring_skills_weight')
    op.create_index(op.f('ix_scorecards_interview_id'), 'scorecards', ['interview_id'], unique=False)
    op.create_index(op.f('ix_scorecards_evaluator_id'), 'scorecards', ['evaluator_id'], unique=False)
    op.alter_column('scorecards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_tenant_id_fkey'), 'notifications', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notifications_user_read'), 'notifications', ['user_id', 'read', 'created_at'], unique=False)
    op.create_index(op.f('ix_match_sessions_tenant_id'), 'match_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_match_sessions_status'), 'match_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_match_scores_tenant_id'), 'match_scores', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_match_scores_score'), 'match_scores', ['score'], unique=False)
    op.create_index(op.f('ix_match_scores_position_id'), 'match_scores', ['position_id'], unique=False)
    op.create_index(op.f('ix_match_scores_candidate_id'), 'match_scores', ['candidate_id'], unique=False)
    op.alter_column('interviews', 'conversation_metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('interviews', 'tts_audio_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bulk_imports', type_='foreignkey')
    op.drop_constraint(None, 'bulk_imports', type_='foreignkey')
    op.drop_constraint(None, 'bulk_imports', type_='foreignkey')
    op.create_foreign_key(op.f('bulk_imports_user_id_fkey'), 'bulk_imports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bulk_imports_tenant_id_fkey'), 'bulk_imports', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bulk_imports_position_id_fkey'), 'bulk_imports', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_applications_position_id'), 'applications', ['position_id'], unique=False)
    op.create_index(op.f('ix_applications_candidate_position'), 'applications', ['candidate_id', 'position_id'], unique=False)
    # ### end Alembic commands ###
